name = "clarkson"
uuid = "1334b51b-9357-4543-a871-e3ede020c76d"
authors = ["deft gur <ziwenhehe@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WeightVectors = "02edb123-fbf3-4025-abe6-bed5b7376cdf"

[compat]
BenchmarkTools = "1.6.3"
CodecZlib = "0.7.8"
IterativeSolvers = "0.9.4"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
TimerOutputs = "0.5.29"
